### PR TITLE
trying to fix #4 - Too many publishes

### LINKED ISSUE #4: c.h.cloudio.endpoint.CloudioEndpoint - Exception :Too many publishes in progress
We are seeing a lot of :
```
c.h.cloudio.endpoint.CloudioEndpoint - Exception :Too many publishes in progress
Too many publishes in progress (32202)
org.eclipse.paho.client.mqttv3.internal.ClientState.send(ClientState.java:436)
org.eclipse.paho.client.mqttv3.internal.ClientComms.internalSend(ClientComms.java:121)
org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:139)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:858)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:822)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:829)
ch.hevs.cloudio.endpoint.CloudioEndpoint$InternalEndpoint.attributeHasChangedByEndpoint(CloudioEndpoint.java:558)
ch.hevs.cloudio.endpoint.CloudioNode$InternalNode.attributeHasChangedByEndpoint(CloudioNode.java:66)
ch.hevs.cloudio.endpoint.CloudioObject$InternalObject.attributeHasChangedByEndpoint(CloudioObject.java:132)
ch.hevs.cloudio.endpoint.CloudioAttribute.setValue(CloudioAttribute.java:90)
GoflexPusher.run(GoflexPusher.java:50)
java.lang.Thread.run(Thread.java:745)
```

We have tried to push less messages, but the solution is probably to change some connection parameters in `cloudio-java-endpoint`. I'm currently testing some changes.

### PR DESCRIPTION
**Pull request by RandomReaper**
It seems that we have some problems when trying to publish too many messages,
paho v1.2 has introduced setMaxInflight, so let's use it.

* Updated to org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0
* Added the ch.hevs.cloudio.endpoint.maxInFlight property (default to 1000 instead of 10 in paho)

### CODE REVIEW

**Comment by RandomReaper** [comment]
This patch is currently in test since October 11, in the goflex project. There is no more `c.h.cloudio.endpoint.CloudioEndpoint - Exception :Too many publishes in progress`, so the problem seems to be fixed.

File: endpoint/cloudio-endpoint-java/src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java [hunk 1]
```diff
@@ -512,6 +514,16 @@ public InternalEndpoint(String uuid, CloudioEndpointConfiguration configuration,
                         "(ch.hevs.cloudio.endpoint.keepAliveInterval), " +
                         "must be a valid integer number");
             }
+            
+            // Get the maxInFlight property.
+            try {
+                options.setMaxInflight(Integer.parseInt(
+                    configuration.getProperty(MQTT_MAXINFLIGHT_PROPERTY, MQTT_MAXINFLIGHT_DEFAULT)));
+            } catch (NumberFormatException exception) {
+                throw new InvalidPropertyException("Invalid keep alive interval " +
```
Comment (cm0x4D) [inline endpoint/cloudio-endpoint-java/src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java]: Could you just change the error message, seems to be a copy/paste error.

**Comment by RandomReaper** [comment]
Done in 29d192deff0e41be110279726964d4116bf2b339

**Comment by cm0x4D** [comment]
Thanks for the contribution
